#!/bin/sh
ssh ubuntu@3.38.219.157 <<EOF
    cd ~/ovni		
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 14.19.3
    npm install
    npm install -g typescript
    npm install -g ts-node
    npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF
